global:
  scrape_interval: 2s
  evaluation_interval: 2s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "Gateway-Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8880"]
        labels:
          application: Gateway-Service

  - job_name: "RRMS"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:10000"]
        labels:
          application: "RRMS"
