INSERT INTO users (id, created_at, created_by, deleted_at, deleted_by, updated_at, updated_by, address_proof,
                   assignment_code, bank_account_name, bank_account_number, bank_account_picture, date_of_birth, email,
                   emergency_contact, emergency_relationship, id_card_back, id_card_front, last_login_at,
                   national_id, nationality, password, phone_number, preferred_location, profile_picture,
                   provider, user_status, username, verified, verify_code, fullname, gender, preferred_language)
VALUES ('a9f38679-09bf-4ba4-ab4b-9ea5224beb32', '2024-11-23 03:00:04.809989 +00:00',
        'a9f38679-09bf-4ba4-ab4b-9ea5224beb32', null, null,
        '2024-11-23 03:00:04.809998 +00:00', null, null, '95388b', null, null, null, null, 'super.admin@rrms.com', null,
        null, null, null, null, null, null,
        '$2a$10$nRLYbv1te1iWk0hIZA.GGOaOc5qWuub.bLI1J7CsS9GJZ9ez/qFcq',
        null, null, null, 'LOCAL', 'ACTIVE', 'superadmin', null, '2f2ce49c-7f7f-4679-833c-21e3c689ab17', 'superadmin',
        'MALE', null);
