name: Measure Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', 'pom.xml') || github.sha }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests Coverage
        run: mvn -B test verify --file pom.xml -Pcoverage

      - name: JaCoCo Report
        id: jacoco-report
        uses: Madrapps/jacoco-report@v1.7.1
        with:
          title: '# :lobster: Coverage Report'
          paths: target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60



